name: islamic_reminder
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.7.3
  intl: ^0.20.0
  tostore: ^2.2.2
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  upgrader: ^12.1.0
  firebase_crashlytics: ^5.0.3
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0
  device_info_plus: ^11.0.0
  cached_network_image: ^3.4.1
  google_mobile_ads: ^6.0.0
  lottie: ^3.3.1
  connecteo: ^3.0.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  stacked_generator: ^1.3.3
  mockito: ^5.4.1
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
